AMREX_HOME ?= ../../../../../amrex

DEBUG	= TRUE
DEBUG	= FALSE

DIM	= 2

COMP    = gcc

TINY_PROFILE  = TRUE
USE_PARTICLES = TRUE

PRECISION     = DOUBLE

USE_MPI       = TRUE
USE_OMP       = FALSE
USE_ACC       = FALSE
USE_CUDA      = FALSE

Blocs   := .

include ../Make.ESPIC
