name: windows

on: [push, pull_request]

jobs:
  # Build all tutorials
  tests_msvc:
    name: MSVC w/o Fortran w/o MPI
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build & Install
      run: |
        cd ExampleCodes
        cmake -S . -B build   `
              -DCMAKE_BUILD_TYPE=Debug      `
              -DBUILD_SHARED_LIBS=ON        `
              -DCMAKE_VERBOSE_MAKEFILE=ON   `
              -DAMReX_FORTRAN=OFF           `
              -DAMReX_MPI=OFF               `
              -DAMReX_LINEAR_SOLVERS=ON     `
              -DAMReX_EB=ON                 `
              -DAMReX_PARTICLES=ON
        cmake --build build --config Debug -j 2

  # Build all tutorials
  tutorials_clang:
    name: Clang w/o Fortran w/o MPI
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v6
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Set Up MSVC
      uses: ilammy/msvc-dev-cmd@v1
    - name: Build & Install
      shell: cmd
      run: |
        cd ExampleCodes
        cmake -S . -B build   ^
              -G Ninja                  ^
              -DCMAKE_C_COMPILER=clang-cl ^
              -DCMAKE_CXX_COMPILER=clang-cl ^
              -DCMAKE_CXX_STANDARD=20       ^
              -DCMAKE_BUILD_TYPE=Release    ^
              -DBUILD_SHARED_LIBS=ON        ^
              -DCMAKE_VERBOSE_MAKEFILE=ON   ^
              -DAMReX_FORTRAN=OFF           ^
              -DAMReX_MPI=OFF               ^
              -DAMReX_OMP=ON                ^
              -DAMReX_LINEAR_SOLVERS=ON     ^
              -DAMReX_EB=ON                 ^
              -DAMReX_PARTICLES=ON
        cmake --build build --config Release -j 2
